const mutation_types = {
    INCREMENT: 'INCREMENT',
    SETOPTIONS: 'SETOPTIONS',
    SETSOLUTION: 'SETSOLUTION',
    ADDLOG: 'ADDLOG',
    SETCURRENTMODULEINDEX: 'SETCURRENTMODULEINDEX'
}

export default mutation_types